---
version: "3"

dotenv: ['.env']

tasks:
  install:
    desc: "Install dependencies"
    cmds:
      - npm install

  dev:
    desc: "Start development server with hot reload"
    cmds:
      - npm run dev

  build:
    desc: "Build for production"
    cmds:
      - npm run build

  preview:
    desc: "Preview production build"
    cmds:
      - npm run preview

  check:
    desc: "Run all checks"
    cmds:
      - npm run check

  format:
    desc: "Auto-fix formatting and linting issues"
    cmds:
      - npm run format

  clean:
    desc: "Clean build artifacts and dependencies"
    cmds:
      - rm -rf dist node_modules .vite

  clean:cache:
    desc: "Clean build cache"
    cmds:
      - rm -rf dist .vite

  test:
    desc: "Run tests"
    cmds:
      - npm test

  generate-openapi:
    desc: "Generate OpenAPI Zod schemas using orval"
    cmds:
      - mkdir -p src/api
      - rm -f src/api/types.gen.ts
      - npx orval
