// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthenticateRequest defines model for AuthenticateRequest.
type AuthenticateRequest struct {
	LoginID  string `binding:"required,max=100" json:"loginId"`
	Password string `binding:"required,min=8,max=20" json:"password"`
}

// AuthenticateResponse defines model for AuthenticateResponse.
type AuthenticateResponse struct {
	AccessToken string `json:"accessToken"`
}

// CreateBulkTodosRequest defines model for CreateBulkTodosRequest.
type CreateBulkTodosRequest struct {
	Todos []CreateTodoRequest `json:"todos"`
}

// CreateBulkTodosResponse defines model for CreateBulkTodosResponse.
type CreateBulkTodosResponse struct {
	Todos []CreateTodoResponse `json:"todos"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Text string `binding:"required,max=250" json:"text"`
}

// CreateTodoResponse defines model for CreateTodoResponse.
type CreateTodoResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FindTodoResponse defines model for FindTodoResponse.
type FindTodoResponse struct {
	Todos []FindTodoResponseTodo `json:"todos"`
}

// FindTodoResponseTodo defines model for FindTodoResponseTodo.
type FindTodoResponseTodo struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	IsComplete bool   `json:"isComplete"`
	Text       string `binding:"required,max=250" json:"text"`
}

// UpdateTodoResponse defines model for UpdateTodoResponse.
type UpdateTodoResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// AuthenticateJSONRequestBody defines body for Authenticate for application/json ContentType.
type AuthenticateJSONRequestBody = AuthenticateRequest

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// CreateBulkTodosJSONRequestBody defines body for CreateBulkTodos for application/json ContentType.
type CreateBulkTodosJSONRequestBody = CreateBulkTodosRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest
