// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	CookieAuthScopes = "CookieAuth.Scopes"
)

// Defines values for AuthenticateParamsXTokenDelivery.
const (
	Cookie AuthenticateParamsXTokenDelivery = "cookie"
	Json   AuthenticateParamsXTokenDelivery = "json"
)

// AuthenticateRequest defines model for AuthenticateRequest.
type AuthenticateRequest struct {
	LoginID  string `binding:"required,max=100" json:"loginId"`
	Password string `binding:"required,min=8,max=20" json:"password"`
}

// AuthenticateResponse Authentication response. When X-Token-Delivery is 'json' (default), accessToken is returned in the body. When 'cookie', the token is delivered via Set-Cookie header and accessToken is omitted.
type AuthenticateResponse struct {
	// AccessToken JWT access token (omitted when delivered via cookie)
	AccessToken *string `json:"accessToken,omitempty"`
}

// CreateBulkTodosRequest defines model for CreateBulkTodosRequest.
type CreateBulkTodosRequest struct {
	Todos []CreateTodoRequest `json:"todos"`
}

// CreateBulkTodosResponse defines model for CreateBulkTodosResponse.
type CreateBulkTodosResponse struct {
	Todos []CreateTodoResponse `json:"todos"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Text string `binding:"required,max=250" json:"text"`
}

// CreateTodoResponse defines model for CreateTodoResponse.
type CreateTodoResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FindTodoResponse defines model for FindTodoResponse.
type FindTodoResponse struct {
	Todos []FindTodoResponseTodo `json:"todos"`
}

// FindTodoResponseTodo defines model for FindTodoResponseTodo.
type FindTodoResponseTodo struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// GetMeResponse defines model for GetMeResponse.
type GetMeResponse struct {
	LoginID string `json:"loginId"`
	UserID  int32  `json:"userId"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	IsComplete bool   `json:"isComplete"`
	Text       string `binding:"required,max=250" json:"text"`
}

// UpdateTodoResponse defines model for UpdateTodoResponse.
type UpdateTodoResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	ID         int32     `json:"id"`
	IsComplete bool      `json:"isComplete"`
	Text       string    `json:"text"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// AuthenticateParams defines parameters for Authenticate.
type AuthenticateParams struct {
	// XTokenDelivery Token delivery method (json or cookie)
	XTokenDelivery *AuthenticateParamsXTokenDelivery `json:"X-Token-Delivery,omitempty"`
}

// AuthenticateParamsXTokenDelivery defines parameters for Authenticate.
type AuthenticateParamsXTokenDelivery string

// AuthenticateJSONRequestBody defines body for Authenticate for application/json ContentType.
type AuthenticateJSONRequestBody = AuthenticateRequest

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// CreateBulkTodosJSONRequestBody defines body for CreateBulkTodos for application/json ContentType.
type CreateBulkTodosJSONRequestBody = CreateBulkTodosRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest
