---
report-formats: json
no-progress: true
no-color: true
minimal-ui: true
enable_comments: true
exclude-paths:
  - /path/openapi
  - openapi
exclude-severities:
  - low
  - info
exclude-queries:
  # Healthcheck Not Set
  - 698ed579-b239-4f8f-a388-baa4bcb13ef8
