---
version: "2"
run:
  go: "1.25"
  build-tags:
    - small
    - medium
    - large
linters:
  enable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - importas
    - makezero
    - mirror
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - whitespace
    - wrapcheck
    - wsl_v5

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 12
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
    wrapcheck:
      extra-ignore-sigs:
        - errors.Errorf(
        - .Errorf(
        - .Errorf
        - liberrors.Errorf(
      ignore-sigs:
        - errors.Errorf(
        - .Errorf(
        - .Errorf
        - errors.New(
        - liberrors.Errorf(
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - if
        - expr
        - switch
        - append
        - range
        - assign
        - decl
        - return
        - defer
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - dupl
          - wsl_v5
          - revive
          - exhaustruct
          - wrapcheck
          - goconst
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
