---
services:
  local-todo-otel-collector-base:
    image: otel/opentelemetry-collector-contrib:0.138.0
    container_name: local-todo-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - NET_RAW
      - SETFCAP
      - SYS_CHROOT
