---
version: "3"

tasks:
  check:
    cmds:
      - task: check:backend-gin-gorm

  check:backend-gin-gorm:
    cmds:
      - task -d backend-gin-gorm check

  kics:
    cmds:
      - docker run -t -v ./:/path checkmarx/kics scan -p /path --config /path/.github/kics.yml

  test:
    cmds:
      - task: test:backend-gin-gorm

  test:backend-gin-gorm:
    cmds:
      - task -d backend-gin-gorm test

  download-openapi-yaml:
    desc: "Download openapi.yaml from Apidog"
    cmds:
      - scripts/download-openapi-yaml.sh
      - mv openapi.yaml openapi/openapi.yaml
      - echo "✅ openapi.yaml downloaded to openapi/openapi.yaml"
