---
version: "3"

tasks:
  check:
    cmds:
      - task -d backend-gin-gorm check
      - task -d frontend-react-zustand check
      - task -d frontend-flutter check
      - spectral lint openapi/openapi.yaml --ruleset .spectral.yaml

  kics:
    cmds:
      - docker run -t -v ./:/path checkmarx/kics scan -p /path --config /path/.github/kics.yml

  test:
    cmds:
      - task -d backend-gin-gorm test
      - task -d frontend-flutter test

  download-openapi-yaml:
    desc: "Download openapi.yaml from Apidog"
    cmds:
      - scripts/download-openapi-yaml.sh
      - mv openapi.yaml openapi/openapi.yaml
      - echo "openapi.yaml downloaded to openapi/openapi.yaml"

  generate-openapi:
    desc: "Generate OpenAPI models"
    cmds:
      - task -d backend-gin-gorm generate-openapi
      - task -d frontend-react-zustand generate-openapi
