---
version: "3"

dotenv: ['.env']

tasks:
  check:
    cmds:
      - golangci-lint run --config ../.golangci.yml --timeout=5m

  air:
    cmds:
      - docker compose -f compose.local.air.yml up

  run:
    cmds:
      - docker compose -f compose.local.collector-tui.yml up -d --wait
      - go run .
    env:
      APP_ENV: local
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: local
      TRACE_EXPORTER: otlphttp
      LOG_EXPORTER: none
  clear-local:
    cmds:
      - docker compose -f compose.local.collector-tui.yml down

  test:
    cmds:
      - docker compose -f compose.test.yml up -d --wait
      - go test -coverprofile=coverage.out ./... -tags=medium --count=1
      - gcov2lcov -infile=coverage.out -outfile=coverage.lcov
    env:
      APP_ENV: test
      TEST_MYSQL_HOST: localhost
      TEST_MYSQL_PORT: 3307
      TEST_MYSQL_USERNAME: username
      TEST_MYSQL_PASSWORD: password
      TEST_MYSQL_DATABASE: test
  clear-test:
    cmds:
      - docker compose -f compose.test.yml down

  generate-openapi:
    desc: "Generate OpenAPI models using oapi-codegen"
    cmds:
      - mkdir -p api
      - rm -r api/types.gen.go
      - oapi-codegen -package=api -generate=models -o=api/types.gen.go ../openapi/openapi.yaml
      - go fmt api/types.gen.go || true
      - echo "Models generated"
