// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase_test

import (
	"github.com/mocoarow/todo-apps/backend-gin-gorm/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthTokenCreator creates a new instance of MockAuthTokenCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenCreator {
	mock := &MockAuthTokenCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenCreator is an autogenerated mock type for the AuthTokenCreator type
type MockAuthTokenCreator struct {
	mock.Mock
}

type MockAuthTokenCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenCreator) EXPECT() *MockAuthTokenCreator_Expecter {
	return &MockAuthTokenCreator_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockAuthTokenCreator
func (_mock *MockAuthTokenCreator) CreateToken(loginID string, userID int) (string, error) {
	ret := _mock.Called(loginID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return returnFunc(loginID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = returnFunc(loginID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(loginID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenCreator_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockAuthTokenCreator_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - loginID string
//   - userID int
func (_e *MockAuthTokenCreator_Expecter) CreateToken(loginID interface{}, userID interface{}) *MockAuthTokenCreator_CreateToken_Call {
	return &MockAuthTokenCreator_CreateToken_Call{Call: _e.mock.On("CreateToken", loginID, userID)}
}

func (_c *MockAuthTokenCreator_CreateToken_Call) Run(run func(loginID string, userID int)) *MockAuthTokenCreator_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenCreator_CreateToken_Call) Return(s string, err error) *MockAuthTokenCreator_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthTokenCreator_CreateToken_Call) RunAndReturn(run func(loginID string, userID int) (string, error)) *MockAuthTokenCreator_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthTokenParser creates a new instance of MockAuthTokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenParser {
	mock := &MockAuthTokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenParser is an autogenerated mock type for the AuthTokenParser type
type MockAuthTokenParser struct {
	mock.Mock
}

type MockAuthTokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenParser) EXPECT() *MockAuthTokenParser_Expecter {
	return &MockAuthTokenParser_Expecter{mock: &_m.Mock}
}

// ParseToken provides a mock function for the type MockAuthTokenParser
func (_mock *MockAuthTokenParser) ParseToken(tokenString string) (*domain.UserInfo, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *domain.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.UserInfo, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.UserInfo); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenParser_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockAuthTokenParser_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockAuthTokenParser_Expecter) ParseToken(tokenString interface{}) *MockAuthTokenParser_ParseToken_Call {
	return &MockAuthTokenParser_ParseToken_Call{Call: _e.mock.On("ParseToken", tokenString)}
}

func (_c *MockAuthTokenParser_ParseToken_Call) Run(run func(tokenString string)) *MockAuthTokenParser_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthTokenParser_ParseToken_Call) Return(userInfo *domain.UserInfo, err error) *MockAuthTokenParser_ParseToken_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockAuthTokenParser_ParseToken_Call) RunAndReturn(run func(tokenString string) (*domain.UserInfo, error)) *MockAuthTokenParser_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
