// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler_test

import (
	"context"

	"github.com/mocoarow/todo-apps/backend-gin-gorm/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTodoUsecase creates a new instance of MockTodoUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTodoUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTodoUsecase {
	mock := &MockTodoUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTodoUsecase is an autogenerated mock type for the TodoUsecase type
type MockTodoUsecase struct {
	mock.Mock
}

type MockTodoUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTodoUsecase) EXPECT() *MockTodoUsecase_Expecter {
	return &MockTodoUsecase_Expecter{mock: &_m.Mock}
}

// CreateBulkTodos provides a mock function for the type MockTodoUsecase
func (_mock *MockTodoUsecase) CreateBulkTodos(ctx context.Context, input *domain.CreateBulkTodosInput) (*domain.CreateBulkTodosOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulkTodos")
	}

	var r0 *domain.CreateBulkTodosOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateBulkTodosInput) (*domain.CreateBulkTodosOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateBulkTodosInput) *domain.CreateBulkTodosOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateBulkTodosOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateBulkTodosInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoUsecase_CreateBulkTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBulkTodos'
type MockTodoUsecase_CreateBulkTodos_Call struct {
	*mock.Call
}

// CreateBulkTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.CreateBulkTodosInput
func (_e *MockTodoUsecase_Expecter) CreateBulkTodos(ctx interface{}, input interface{}) *MockTodoUsecase_CreateBulkTodos_Call {
	return &MockTodoUsecase_CreateBulkTodos_Call{Call: _e.mock.On("CreateBulkTodos", ctx, input)}
}

func (_c *MockTodoUsecase_CreateBulkTodos_Call) Run(run func(ctx context.Context, input *domain.CreateBulkTodosInput)) *MockTodoUsecase_CreateBulkTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateBulkTodosInput
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateBulkTodosInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoUsecase_CreateBulkTodos_Call) Return(createBulkTodosOutput *domain.CreateBulkTodosOutput, err error) *MockTodoUsecase_CreateBulkTodos_Call {
	_c.Call.Return(createBulkTodosOutput, err)
	return _c
}

func (_c *MockTodoUsecase_CreateBulkTodos_Call) RunAndReturn(run func(ctx context.Context, input *domain.CreateBulkTodosInput) (*domain.CreateBulkTodosOutput, error)) *MockTodoUsecase_CreateBulkTodos_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodo provides a mock function for the type MockTodoUsecase
func (_mock *MockTodoUsecase) CreateTodo(ctx context.Context, input *domain.CreateTodoInput) (*domain.CreateTodoOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 *domain.CreateTodoOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateTodoInput) (*domain.CreateTodoOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.CreateTodoInput) *domain.CreateTodoOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateTodoOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.CreateTodoInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoUsecase_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockTodoUsecase_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.CreateTodoInput
func (_e *MockTodoUsecase_Expecter) CreateTodo(ctx interface{}, input interface{}) *MockTodoUsecase_CreateTodo_Call {
	return &MockTodoUsecase_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, input)}
}

func (_c *MockTodoUsecase_CreateTodo_Call) Run(run func(ctx context.Context, input *domain.CreateTodoInput)) *MockTodoUsecase_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.CreateTodoInput
		if args[1] != nil {
			arg1 = args[1].(*domain.CreateTodoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoUsecase_CreateTodo_Call) Return(createTodoOutput *domain.CreateTodoOutput, err error) *MockTodoUsecase_CreateTodo_Call {
	_c.Call.Return(createTodoOutput, err)
	return _c
}

func (_c *MockTodoUsecase_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, input *domain.CreateTodoInput) (*domain.CreateTodoOutput, error)) *MockTodoUsecase_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockTodoUsecase
func (_mock *MockTodoUsecase) DeleteTodo(ctx context.Context, input *domain.DeleteTodoInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DeleteTodoInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTodoUsecase_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockTodoUsecase_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.DeleteTodoInput
func (_e *MockTodoUsecase_Expecter) DeleteTodo(ctx interface{}, input interface{}) *MockTodoUsecase_DeleteTodo_Call {
	return &MockTodoUsecase_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, input)}
}

func (_c *MockTodoUsecase_DeleteTodo_Call) Run(run func(ctx context.Context, input *domain.DeleteTodoInput)) *MockTodoUsecase_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DeleteTodoInput
		if args[1] != nil {
			arg1 = args[1].(*domain.DeleteTodoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoUsecase_DeleteTodo_Call) Return(err error) *MockTodoUsecase_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTodoUsecase_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, input *domain.DeleteTodoInput) error) *MockTodoUsecase_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// FindTodos provides a mock function for the type MockTodoUsecase
func (_mock *MockTodoUsecase) FindTodos(ctx context.Context, userID int) ([]*domain.Todo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindTodos")
	}

	var r0 []*domain.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Todo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*domain.Todo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoUsecase_FindTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTodos'
type MockTodoUsecase_FindTodos_Call struct {
	*mock.Call
}

// FindTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTodoUsecase_Expecter) FindTodos(ctx interface{}, userID interface{}) *MockTodoUsecase_FindTodos_Call {
	return &MockTodoUsecase_FindTodos_Call{Call: _e.mock.On("FindTodos", ctx, userID)}
}

func (_c *MockTodoUsecase_FindTodos_Call) Run(run func(ctx context.Context, userID int)) *MockTodoUsecase_FindTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoUsecase_FindTodos_Call) Return(todos []*domain.Todo, err error) *MockTodoUsecase_FindTodos_Call {
	_c.Call.Return(todos, err)
	return _c
}

func (_c *MockTodoUsecase_FindTodos_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]*domain.Todo, error)) *MockTodoUsecase_FindTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockTodoUsecase
func (_mock *MockTodoUsecase) UpdateTodo(ctx context.Context, input *domain.UpdateTodoInput) (*domain.UpdateTodoOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 *domain.UpdateTodoOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UpdateTodoInput) (*domain.UpdateTodoOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UpdateTodoInput) *domain.UpdateTodoOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpdateTodoOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UpdateTodoInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTodoUsecase_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockTodoUsecase_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.UpdateTodoInput
func (_e *MockTodoUsecase_Expecter) UpdateTodo(ctx interface{}, input interface{}) *MockTodoUsecase_UpdateTodo_Call {
	return &MockTodoUsecase_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, input)}
}

func (_c *MockTodoUsecase_UpdateTodo_Call) Run(run func(ctx context.Context, input *domain.UpdateTodoInput)) *MockTodoUsecase_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UpdateTodoInput
		if args[1] != nil {
			arg1 = args[1].(*domain.UpdateTodoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTodoUsecase_UpdateTodo_Call) Return(updateTodoOutput *domain.UpdateTodoOutput, err error) *MockTodoUsecase_UpdateTodo_Call {
	_c.Call.Return(updateTodoOutput, err)
	return _c
}

func (_c *MockTodoUsecase_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, input *domain.UpdateTodoInput) (*domain.UpdateTodoOutput, error)) *MockTodoUsecase_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}
