CREATE TABLE `todo` (
 `id` INT NOT NULL AUTO_INCREMENT
,`user_id` INT NOT NULL
,`text` VARCHAR(255) NOT NULL
,`is_complete` BOOLEAN NOT NULL DEFAULT FALSE
,`created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
,`updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
,PRIMARY KEY (`id`)
,KEY `idx_todo_user_id` (`user_id`)
);
