/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Todo App API
 * A Todo application API with authentication
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

/**
 * Authenticate user with login ID and password
 * @summary User authentication
 */
export const authenticateHeaderXTokenDeliveryDefault = `json`;

export const AuthenticateHeader = zod.object({
  "X-Token-Delivery": zod.enum(['json', 'cookie']).default(authenticateHeaderXTokenDeliveryDefault).describe('Token delivery method (json or cookie)')
})

export const authenticateBodyLoginIdMax = 100;


export const authenticateBodyLoginIdRegExp = new RegExp('^.\*$');
export const authenticateBodyPasswordMin = 8;
export const authenticateBodyPasswordMax = 20;


export const authenticateBodyPasswordRegExp = new RegExp('^.\*$');


export const AuthenticateBody = zod.object({
  "loginId": zod.string().max(authenticateBodyLoginIdMax).regex(authenticateBodyLoginIdRegExp),
  "password": zod.string().min(authenticateBodyPasswordMin).max(authenticateBodyPasswordMax).regex(authenticateBodyPasswordRegExp)
})

export const authenticateResponseAccessTokenRegExp = new RegExp('^.\*$');


export const AuthenticateResponse = zod.object({
  "accessToken": zod.string().regex(authenticateResponseAccessTokenRegExp).optional().describe('JWT access token (omitted when delivered via cookie)')
}).describe('Authentication response. When X-Token-Delivery is \'json\' (default), accessToken is returned in the body. When \'cookie\', the token is delivered via Set-Cookie header and accessToken is omitted.')


/**
 * Get the authenticated user's information
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  "userId": zod.number(),
  "loginId": zod.string()
})


/**
 * Get all todos for the authenticated user
 * @summary Get all todos
 */
export const getTodosResponseTodosItemTextMax = 250;


export const getTodosResponseTodosItemTextRegExp = new RegExp('^.\*$');
export const getTodosResponseTodosMax = 100;



export const GetTodosResponse = zod.object({
  "todos": zod.array(zod.object({
  "id": zod.number(),
  "text": zod.string().max(getTodosResponseTodosItemTextMax).regex(getTodosResponseTodosItemTextRegExp),
  "isComplete": zod.boolean(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})).max(getTodosResponseTodosMax)
})


/**
 * Create a new todo for the authenticated user
 * @summary Create a new todo
 */
export const createTodoBodyTextMax = 250;


export const createTodoBodyTextRegExp = new RegExp('^.\*$');


export const CreateTodoBody = zod.object({
  "text": zod.string().max(createTodoBodyTextMax).regex(createTodoBodyTextRegExp)
})


/**
 * Create multiple todos for the authenticated user in a single request
 * @summary Create multiple todos
 */
export const createBulkTodosBodyTodosItemTextMax = 250;


export const createBulkTodosBodyTodosItemTextRegExp = new RegExp('^.\*$');
export const createBulkTodosBodyTodosMax = 100;



export const CreateBulkTodosBody = zod.object({
  "todos": zod.array(zod.object({
  "text": zod.string().max(createBulkTodosBodyTodosItemTextMax).regex(createBulkTodosBodyTodosItemTextRegExp)
})).min(1).max(createBulkTodosBodyTodosMax)
})


/**
 * Update an existing todo for the authenticated user
 * @summary Update a todo
 */
export const UpdateTodoParams = zod.object({
  "id": zod.number().describe('Todo ID')
})

export const updateTodoBodyTextMax = 250;


export const updateTodoBodyTextRegExp = new RegExp('^.\*$');


export const UpdateTodoBody = zod.object({
  "text": zod.string().max(updateTodoBodyTextMax).regex(updateTodoBodyTextRegExp),
  "isComplete": zod.boolean()
})

export const updateTodoResponseTextMax = 250;


export const updateTodoResponseTextRegExp = new RegExp('^.\*$');


export const UpdateTodoResponse = zod.object({
  "id": zod.number(),
  "text": zod.string().max(updateTodoResponseTextMax).regex(updateTodoResponseTextRegExp),
  "isComplete": zod.boolean(),
  "createdAt": zod.iso.datetime({}),
  "updatedAt": zod.iso.datetime({})
})


/**
 * Delete an existing todo for the authenticated user
 * @summary Delete a todo
 */
export const DeleteTodoParams = zod.object({
  "id": zod.number().describe('Todo ID')
})
