// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package middleware_test

import (
	"github.com/mocoarow/todo-apps/backend-gin-gorm/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type MockAuthUsecase
func (_mock *MockAuthUsecase) GetUserInfo(input *domain.GetUserInfoInput) (*domain.GetUserInfoOutput, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *domain.GetUserInfoOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.GetUserInfoInput) (*domain.GetUserInfoOutput, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.GetUserInfoInput) *domain.GetUserInfoOutput); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetUserInfoOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.GetUserInfoInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthUsecase_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthUsecase_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - input *domain.GetUserInfoInput
func (_e *MockAuthUsecase_Expecter) GetUserInfo(input interface{}) *MockAuthUsecase_GetUserInfo_Call {
	return &MockAuthUsecase_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", input)}
}

func (_c *MockAuthUsecase_GetUserInfo_Call) Run(run func(input *domain.GetUserInfoInput)) *MockAuthUsecase_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.GetUserInfoInput
		if args[0] != nil {
			arg0 = args[0].(*domain.GetUserInfoInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthUsecase_GetUserInfo_Call) Return(getUserInfoOutput *domain.GetUserInfoOutput, err error) *MockAuthUsecase_GetUserInfo_Call {
	_c.Call.Return(getUserInfoOutput, err)
	return _c
}

func (_c *MockAuthUsecase_GetUserInfo_Call) RunAndReturn(run func(input *domain.GetUserInfoInput) (*domain.GetUserInfoOutput, error)) *MockAuthUsecase_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
